name: CI

on:
  pull_request:
    branches: 
      - lauck

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo Installing Packer...
        export VER="1.5.1"
        wget https://releases.hashicorp.com/packer/${VER}/packer_${VER}_linux_amd64.zip
        unzip packer_${VER}_linux_amd64.zip
        sudo mv packer /usr/local/bin
        echo Validating Packer Install...
        packer --version
        packer validate packer_templates/centos/centos-7.7-x86_64.json
        packer build -only=virtualbox-iso packer_templates/centos/centos-7.7-x86_64.json